# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '36 23 * * *'
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      # Runs a single command using the runners shell
      - name: Build
        run: echo "Buil"!

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Teste
        run: echo "teste"!

   
  deploy:
    runs-on: ubuntu-latest
    needs: test  
    
    steps:
        
      - name: Deploy
        run: echo "Deploy"
